version: 3

vars:
  PYTHON: python3
  PIP: pip3
  PROJECTPYTHON: ".mbse/bin/{{.PYTHON}}"
  PROJECTPIP: ".mbse/bin/{{.PIP}}"
  MBSEENV: ".mbse"
  PROJECTFLASK: ".mbse/bin/flask"

tasks:
  init:
    desc: Setup python virtual environment and install requirements
    cmds:
      - "{{.PYTHON}} -m venv {{.MBSEENV}}"
      - "{{.PROJECTPIP}} install --upgrade pip"
      - "{{.PROJECTPIP}} install -r requirements.txt"
      - "{{.PROJECTPIP}} install -e ."

  install:
    desc: Install python package using project PIP. Usage `task install -- <python_package>`
    cmds:
      - "{{.PROJECTPIP}} install {{.CLI_ARGS}}"
      - "{{.PROJECTPIP}} freeze >  requirements.txt"

  install-reqs:
    desc: Install requirements
    cmds:
      - "{{.PROJECTPIP}} install -r requirements.txt"

  test:
    desc: Run tests
    cmds:
      - "{{.PROJECTPYTHON}} -m unittest discover"

  run:
    desc: Run simulation
    cmds:
      - echo "Running simulation with:"
      - cat {{.CLI_ARGS}}
      - "{{.PROJECTPYTHON}} main.py {{.CLI_ARGS}}"
      - notify-send "Simulation done" "Simulation is done"

  flask:
    desc: Run flask
    cmds:
      - "{{.PROJECTFLASK}} run"
